#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Mar  7 10:14:33 2020

@author: david
"""

a = [[1,2,3], [3,2,1]]
b = [[2,2,2], [1,1,1]]

def add(*args):
    count = len(args)
    main = []
    
    for i in args[0]:
        row =[]
        for j in args[0]:
            number = 0
            for item in args:
                number += item[i][j]
            row.append(number)
        main.append(row)
        
            
    
    #main = [x for item in args for x in row]
    
    # use zip
    
    
# =============================================================================
#     
#     for item     :
#         
#         new_list = [expression(i) for i in old_list if filter(i)]
#    [[el - 1 for el in row] for row in matrix]
# =============================================================================
